# Generated by Django 4.0.6 on 2023-03-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairhireapp', '0005_complaints_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
